#
# SPDX-License-Identifier: Apache-2.0
#
---
trigger:
- master

pool:
  vmImage: "ubuntu-latest"

steps:
- task: NodeTool@0
  inputs:
    versionSpec: "12.x"
  displayName: Use Node.js 12.x
- script: npm ci
  displayName: Install dependencies
- script: npm audit
  displayName: Audit dependencies
- script: npm test
  displayName: Run unit tests
